name: Docker Image CI

on:
  push:
    branches: [ feature/refactor-structure ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./grobid_superconductors_python --file ./grobid_superconductors_python/Dockerfile --tag grobid-superconductors-tools:latest
