name: Docker Image CI falcon

on:
  workflow_run:
    workflows: [ "Python CI" ]
    branches: [ master ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lfoppiano/grobid-superconductors-tools:latest
